### PR TITLE
make fields smaller, set engine and charset on tables

### PR DESCRIPTION
**Pull request by matthew-lucidchart**

### CODE REVIEW

**Comment by disaacson** [comment]
How about 100 chars. Let's also reduce the amount of job history entries we keep.

**Comment by disaacson** [comment]
I reduced the days the JobHistoryCleanup job uses to remove entries from 14 to 10 days.

**Comment by matthew-lucidchart** [comment]
if we didn't have the 1 entry of size 68, i would have suggested we make it 50. It's pretty hard not to come up with a unique, descriptive, readable name in under 50 characters.

i was going to get the 68 character one and demonstrate, but i can't find it anymore. either someone changed it or i queried wrong in the first place. max length of all affected fields in all tables is 46.

the tables with 46 are for scheduling and cron expressions. i've made those 100 characters. all job group, job name, trigger group, and trigger name fields are now 50 characters.

the longest trigger name we have is `DirectoryPushNotificationChannelRenewer` which could be renamed to `RenewDirPushNotifyChannel` without losing context or value. that's 46 chars to 26 chars. this wouldn't even be required at our current limit of 50, but shows no loss of value in shortening those fields. it gets even easier if you use the group as it was intended.

**Comment by disaacson** [comment]
I want to balance between what might be optimal for our database and what we could likely submit as a pull request to Quartz. It could be very problematic to diverge from Quartz as the whole purpose of this project is to build on top of Quartz.

Unless you there's a hard quantitative reason to go with 75 over 100 I really think we should use 100 as I think that will be much more palatable to Quartz.

**Comment by matthew-lucidchart** [comment]
done.

**Pull request merged**
